version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://ashish:ashish@152.53.240.143:5432/scheduling_db

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=ashish
      - POSTGRES_PASSWORD=ashish
      - POSTGRES_DB=scheduling_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: